MINIFICPP-1425 Proceed to partial C++20 support
squashed:
commit baa3f502d8fdc6a395983295c8f4187c088765d5
Author: Marton Szasz <szaszm@apache.org>
Date:   Sun Jul 25 14:07:11 2021 +0200

    patch sol2 to not fail in C++20 mode

    on mac xcode/AppleClang, due to const char*/const char8_t*
    incompatibility and the fact that u8"string" literals are now
    const char8*.

    error: invalid conversion from 'const char8_t*' to 'const char*'
    (and friends)

commit 8d6476be877d14e64db25bbdc71adc30b5fc9dd6
Author: Marton Szasz <szaszm@apache.org>
Date:   Wed Jul 21 07:00:26 2021 +0200

    back to C++20